add v10 support
zeldamods/oead pull request #36
Opened 2024-07-02 03:01 UTC by dt-12345

added support for the main v7 features and reading for up to v10 (I didn't add the v10 non-container root nodes though)
wasn't entirely sure how to handle the file nodes (0xa2) so I ended up creating a new struct (also renamed byml::Hash to byml::Dictionary as we have proper hash nodes now)
tested on several files from totk and everything seemed to be fine

2024-07-02 03:47 UTC, dt-12345 commented
added updated strings for totk aamp files (I figured it's at least somewhat relevant)

2024-07-02 17:00 UTC, leoetlino commented
ooh nice! thanks for the pull request, I never got around to doing this

I'll review this later this week

2024-07-07 19:43 UTC, leoetlino requested changes
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/zeldamods/oead/36)* status: all files reviewed (commit messages unreviewed), 7 unresolved discussions (waiting on @dt-12345)

___
*[`readme.rst` line 15 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1D_HmQ9bPoiAIExObc:-O1D_HmQ9bPoiAIExObd:b-8pcqt9) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/readme.rst#L15)):*
> ```reStructuredText
> 
> * `AAMP <https://zeldamods.org/wiki/AAMP>`_ (binary parameter archive): Only version 2 is supported.
> * `BYML <https://zeldamods.org/wiki/BYML>`_ (binary YAML): Versions 1-4 are fully supported, version 5-10 have partial support.
> ```

could you document what is or isn't supported?
___
*[`src/byml.cpp` line 63 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1D_ylxBkmUfLYdDu5s:-O1D_ylxBkmUfLYdDu5t:b-zc4c28) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml.cpp#L63)):*
> ```cpp
>   String = 0xa0,
>   Binary = 0xa1,
>   File = 0xa2,
> ```

can we call this BinaryWithAlignment to keep this consistent with 0xa1?
___
*[`src/byml.cpp` line 254 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1Dd4Ab5cjtyjAczuI7:-O1Dd4Ab5cjtyjAczuI8:b45h) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml.cpp#L254)):*
> ```cpp
>       const auto type = m_reader.Read<NodeType>(types_offset + i);
>       const auto hash = m_reader.Read<u32>(offset + 4 + 8 * i);
>       result.emplace(*hash, ParseContainerChildNode(offset + 8 + 8 * i, type.value()));
> ```





_Suggestion:_
```cpp
hash.value()
```
___
*[`src/byml.cpp` line 381 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1DezXY68qKbomLnJPh:-O1DezXY68qKbomLnJPi:b-9fxz31) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml.cpp#L381)):*
> ```cpp
>       return;
>     case Byml::Type::File:
>       writer.Seek(util::AlignUp(data.GetFile().align, writer.Tell() + 8) - 8);
> ```

hmm, are you sure this is correct? intuitively it feels more natural to write the size and alignment first, _then_ align, and then finally write the data, but I haven't looked at the code that reads aligned binary data so what I'm suggesting might not be possible
___
*[`src/byml_text.cpp` line 126 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1Dgr1t1Fo4ZVSYEkER:-O1Dgr1t1Fo4ZVSYEkES:b-sb2329) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml_text.cpp#L126)):*
> ```cpp
>       auto hash = Byml::Hash32{};
>       for (const auto& child : node) {
>         u32 key = std::stoul(child.key().data(), nullptr, 16);
> ```

stoul/stoull aren't safe to use here because the string data isn't null-terminated. can you convert the key string view into a string first?
___
*[`src/byml_text.cpp` line 134 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1Dhcw01lR_zI5jzZQH:-O1Dhcw01lR_zI5jzZQI:b-7ropln) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml_text.cpp#L134)):*
> ```cpp
>       auto hash = Byml::Hash64{};
>       for (const auto& child : node) {
>         u64 key = std::stoull(child.key().data(), nullptr, 16);
> ```

ditto
___
*[`src/byml_text.cpp` line 184 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1DhuBhD0XEBDF0QEcp:-O1DhuBhD0XEBDF0QEcq:b-2f3cpu) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml_text.cpp#L184)):*
> ```cpp
>         [&](const std::vector<u8>& v) {
>           const std::string encoded =
>               absl::Base64Escape(absl::string_view((const char*)v.data(), v.size()));
> ```

`reinterpret_cast<const char*>(v.data())`


<!-- Sent from Reviewable.io -->

2024-07-07 20:23 UTC, dt-12345 commented
> _[`src/byml.cpp` line 381 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1DezXY68qKbomLnJPh:-O1DezXY68qKbomLnJPi:b-9fxz31) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml.cpp#L381)):_
> 
> > ```c++
> >       return;
> >     case Byml::Type::File:
> >       writer.Seek(util::AlignUp(data.GetFile().align, writer.Tell() + 8) - 8);
> > ```
> 
> hmm, are you sure this is correct? intuitively it feels more natural to write the size and alignment first, _then_ align, and then finally write the data, but I haven't looked at the code that reads aligned binary data so what I'm suggesting might not be possible

the parsing code for getting the data is at 0x7101213a3c for totk 1.2.1 and it appears to expect the data to follow directly after the alignment value (this can be confirmed by looking at any of the files in the Effect folder that use this node type)

2024-07-07 20:27 UTC, dt-12345 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldamods/oead/36)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @leoetlino)

___
*[`readme.rst` line 15 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1D_HmQ9bPoiAIExObc:-O1DsBIH2cWX7MT4mH_-:b-896fix) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/readme.rst#L15)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

could you document what is or isn't supported?
</blockquote></details>

Done.
___
*[`src/byml.cpp` line 63 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1D_ylxBkmUfLYdDu5s:-O1Ds8OAEnmOiWCbOcD3:b-896fix) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml.cpp#L63)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

can we call this BinaryWithAlignment to keep this consistent with 0xa1?
</blockquote></details>

Done.
___
*[`src/byml.cpp` line 254 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1Dd4Ab5cjtyjAczuI7:-O1DsC5z-jmquBkB3eAG:b-896fix) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml.cpp#L254)):*
> ```cpp
>       const auto type = m_reader.Read<NodeType>(types_offset + i);
>       const auto hash = m_reader.Read<u32>(offset + 4 + 8 * i);
>       result.emplace(*hash, ParseContainerChildNode(offset + 8 + 8 * i, type.value()));
> ```

Done.
___
*[`src/byml_text.cpp` line 126 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1Dgr1t1Fo4ZVSYEkER:-O1DsDC56kaA5Rwg_wJr:b-896fix) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml_text.cpp#L126)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

stoul/stoull aren't safe to use here because the string data isn't null-terminated. can you convert the key string view into a string first?
</blockquote></details>

Done.
___
*[`src/byml_text.cpp` line 134 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1Dhcw01lR_zI5jzZQH:-O1DsDRr4Iizv7QeVRu_:b-896fix) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml_text.cpp#L134)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/byml_text.cpp` line 184 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1DhuBhD0XEBDF0QEcp:-O1DsDqt1h-eHpwo534C:b-896fix) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml_text.cpp#L184)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

`reinterpret_cast<const char*>(v.data())`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-08 01:40 UTC, leoetlino reviewed
mostly lgtm, just some minor nits. please run clang-format on the files that have been modified in this pull request too

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldamods/oead/36#-:-O1Eznr86593jnvluu2S:b-uob8nu)* status: all files reviewed, 2 unresolved discussions (waiting on @dt-12345)

___
*[`src/byml_text.cpp` line 126 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1Dgr1t1Fo4ZVSYEkER:-O1EzDXBCXf7jqfpv6pt:b369lhv) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml_text.cpp#L126)):*
<details><summary><i>Previously, dt-12345 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: you can use RymlSubstrToStrView to turn the rapidyaml substring into a std::string_view, and then pass that to std::string (which has a constructor overload that takes a string_view).
___
*[`src/byml_text.cpp` line 188 at r4](https://reviewable.io/reviews/zeldamods/oead/36#-O1EzWa82v0XsNOBgz_4:-O1EzWa82v0XsNOBgz_5:b71hdhd) ([raw file](https://github.com/zeldamods/oead/blob/04a5cd2fe8a0d451f24189da247881f1cceb66d3/src/byml_text.cpp#L188)):*
> ```cpp
>         },
>         [&](const BinaryWithAlignment& v) {
>           yml::LibyamlEmitter::MappingScope scope{emitter, "!file", YAML_BLOCK_MAPPING_STYLE};
> ```

maybe we should use !aligned_binary or something like that


<!-- Sent from Reviewable.io -->

2024-07-08 02:12 UTC, dt-12345 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldamods/oead/36)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @leoetlino)

___
*[`src/byml_text.cpp` line 126 at r3](https://reviewable.io/reviews/zeldamods/oead/36#-O1Dgr1t1Fo4ZVSYEkER:-O1F5xpI2nVaeffM1rCQ:b-896fix) ([raw file](https://github.com/zeldamods/oead/blob/9b09f82429b781924eaf33eb90517b78d59d9df0/src/byml_text.cpp#L126)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

nit: you can use RymlSubstrToStrView to turn the rapidyaml substring into a std::string_view, and then pass that to std::string (which has a constructor overload that takes a string_view).
</blockquote></details>

Done.
___
*[`src/byml_text.cpp` line 188 at r4](https://reviewable.io/reviews/zeldamods/oead/36#-O1EzWa82v0XsNOBgz_4:-O1F60s85Aidao5QEKqs:b-inp5gq) ([raw file](https://github.com/zeldamods/oead/blob/04a5cd2fe8a0d451f24189da247881f1cceb66d3/src/byml_text.cpp#L188)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

maybe we should use !aligned_binary or something like that
</blockquote></details>

Done.
I also added a check for !!file since I noticed that's what other tools used for this node


<!-- Sent from Reviewable.io -->

2024-07-08 21:37 UTC, leoetlino approved these changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeldamods/oead/36)* status: all files reviewed, 1 unresolved discussion (waiting on @dt-12345)

___
*[`src/byml_text.cpp` line 188 at r4](https://reviewable.io/reviews/zeldamods/oead/36#-O1EzWa82v0XsNOBgz_4:-O1JGfc2EmMx1pxN3FD_:bksiqj2) ([raw file](https://github.com/zeldamods/oead/blob/04a5cd2fe8a0d451f24189da247881f1cceb66d3/src/byml_text.cpp#L188)):*
<details><summary><i>Previously, dt-12345 wrote…</i></summary><blockquote>

Done.
I also added a check for !!file since I noticed that's what other tools used for this node
</blockquote></details>

!file or !!file?


<!-- Sent from Reviewable.io -->

2024-07-08 21:43 UTC, dt-12345 reviewed
> *[Reviewable](https://reviewable.io/reviews/zeldamods/oead/36)* status: all files reviewed, 1 unresolved discussion (waiting on @leoetlino)

___
*[`src/byml_text.cpp` line 188 at r4](https://reviewable.io/reviews/zeldamods/oead/36#-O1EzWa82v0XsNOBgz_4:-O1JHdBKEe072dQRpHzF:b-ebq7zn) ([raw file](https://github.com/zeldamods/oead/blob/04a5cd2fe8a0d451f24189da247881f1cceb66d3/src/byml_text.cpp#L188)):*
<details><summary><i>Previously, leoetlino (Léo Lam) wrote…</i></summary><blockquote>

!file or !!file?
</blockquote></details>

roead and nx-editor's BymlLibrary both use !!file with two !'s


<!-- Sent from Reviewable.io -->

2024-07-08 21:44 UTC, leoetlino commented
I'm not quite sure why this fails to build on macOS: https://github.com/zeldamods/oead/actions/runs/9832406488/job/27186862601?pr=36#step:6:717

It looks like adding Hash32 and Hash64 to the variant suddenly makes the compiler think that `std::pair<u32/u64/const std::string, oead::Byml>` aren't copy constructible even though Byml should be copy constructible :|

2024-07-08 21:48 UTC, leoetlino approved these changes
lgtm, thanks again for implementing this!

I'm not sure what to do about the macOS build failure - I don't see an obvious explanation for the compile error (and the fact it builds fine with MSVC and Ubuntu's GCC kinda suggests it might be a compiler bug)

> *[Reviewable](https://reviewable.io/reviews/zeldamods/oead/36#-:-O1JIkwm0hWXG6hBupBC:b-cqe03u)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dt-12345)

___
*[`src/byml_text.cpp` line 188 at r4](https://reviewable.io/reviews/zeldamods/oead/36#-O1EzWa82v0XsNOBgz_4:-O1JIasm6DBrL0v9NlFB:b-h85zzj) ([raw file](https://github.com/zeldamods/oead/blob/04a5cd2fe8a0d451f24189da247881f1cceb66d3/src/byml_text.cpp#L188)):*
<details><summary><i>Previously, dt-12345 wrote…</i></summary><blockquote>

roead and nx-editor's BymlLibrary both use !!file with two !'s
</blockquote></details>

oh ok, was just wondering because a previous version of this PR used `!file`


<!-- Sent from Reviewable.io -->

2024-07-08 21:54 UTC, dt-12345 reviewed
hmm that's odd, I don't know much about macOS so I'm not sure how to resolve that

> *[Reviewable](https://reviewable.io/reviews/zeldamods/oead/36#-:-O1JKF6N9wERocSRumGj:bul10gf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dt-12345)



<!-- Sent from Reviewable.io -->

2026-09-21 00:09 UTC, closed without merging